# Generated by Django 4.0.3 on 2022-03-09 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_users_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='username',
        ),
    ]
