# Generated by Django 4.0.3 on 2022-03-10 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
